[platformio]
default_envs = spacepc-development

[env:spacepc-development]
platform = platformio/espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = post:../../scripts/export-flash-layout.py
lib_extra_dirs = ../../shared/lib
monitor_speed = 115200
build_flags =
  -D SPACEPC_PROJECT_ID=\"smart-fan\"
  -D SPACEPC_FIRMWARE_VERSION=\"0.1.0-dev\"
