#!/usr/bin/env python3
"""Generate the sparse Kaldi Mel matrix used by EfficientAT and the firmware."""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import torch
import torchaudio


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    matrix, _ = torchaudio.compliance.kaldi.get_mel_banks(
        128, 1024, 32000, 0.0, 15000.0,
        vtln_low=100.0, vtln_high=-500.0, vtln_warp_factor=1.0)
    matrix = torch.nn.functional.pad(matrix, (0, 1)).numpy().astype(np.float32)
    starts: list[int] = []
    offsets = [0]
    weights: list[float] = []
    for row in matrix:
        nonzero = np.flatnonzero(row)
        if not len(nonzero):
            raise RuntimeError("empty Mel band")
        start, end = int(nonzero[0]), int(nonzero[-1]) + 1
        starts.append(start)
        weights.extend(float(value) for value in row[start:end])
        offsets.append(len(weights))

    def integers(values: list[int], width: int = 16) -> str:
        return "\n".join("    " + ", ".join(map(str, values[i:i + width])) + ","
                         for i in range(0, len(values), width))

    def floats(values: list[float], width: int = 8) -> str:
        return "\n".join("    " + ", ".join(f"{value:.9g}f" for value in values[i:i + width]) + ","
                         for i in range(0, len(values), width))

    content = f"""// Generated by ml/v2/generate_efficientat_dsp_tables.py.
// EfficientAT uses torchaudio.compliance.kaldi.get_mel_banks(128, 1024,
// 32000, 0, 15000). Only the contiguous non-zero triangles are stored.
#pragma once
#include <stdint.h>

static const uint16_t kEfficientAtMelStarts[128] = {{
{integers(starts)}
}};
static const uint16_t kEfficientAtMelOffsets[129] = {{
{integers(offsets)}
}};
static const float kEfficientAtMelWeights[{len(weights)}] = {{
{floats(weights)}
}};
"""
    args.output.write_text(content)
    print(f"wrote {args.output}: {len(weights)} sparse weights")


if __name__ == "__main__":
    main()
